version: '3.8'

services:
  duck_farm_backend:
    build:
      context: ./duck_farm_backend
    container_name: duck_farm_backend
    restart: always
    volumes:
      - ./duck_farm_backend:/app
      - duck_farm_static_volume:/app/duck_farm/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - duck_farm_network

  db:
    image: postgres:13
    container_name: duck_farm_db
    restart: always
    volumes:
      - duck_farm_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: farmmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - duck_farm_network

  redis:
    image: redis:6
    restart: always
    container_name: duck_farm_redis
    networks:
      - duck_farm_network

  duck_farm_frontend:
    build:
      context: ./duck_farm_frontend
      dockerfile: Dockerfile
    container_name: duck_farm_frontend
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - duck_farm_static_volume:/usr/share/nginx/html/static
    networks:
      - duck_farm_network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - duck_farm_backend

networks:
  duck_farm_network:
    driver: bridge

volumes:
  duck_farm_postgres_data:
  duck_farm_static_volume:
