version: '3.8'

services:
  duck_farm_backend:
    build:
      context: ./duck_farm_backend
    container_name: duck_farm_backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./duck_farm_backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  duck_farm_frontend:
    build:
      context: ./duck_farm_frontend
    container_name: duck_farm_frontend
    volumes:
      - ./duck_farm_frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    container_name: duck_farm_db
    volumes:
      - duck_farm_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: farmmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:6
    container_name: duck_farm_redis
    ports:
      - "6380:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: duck_farm_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: prabhat@gmail.com   # Set your pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: postgres         # Set your pgAdmin login password
    ports:
      - "5050:80"  # Map pgAdmin port 80 to host port 5050 (adjust as needed)

volumes:
  duck_farm_postgres_data:
