# Generated by Django 5.0.6 on 2024-06-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duckinfo',
            name='dealer',
        ),
    ]
