# Generated by Django 5.0.6 on 2024-06-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_duckinfo_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duckinfo',
            name='breed',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
