# Generated by Django 5.0.6 on 2024-06-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_eggstock_dailyeggcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('exp_type', models.CharField(choices=[('buy_duck', 'Buy Duck'), ('feed', 'Feed'), ('medicine', 'Medicine'), ('other_stocks', 'Other Stocks')], max_length=100)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='management.dealer')),
            ],
        ),
        migrations.DeleteModel(
            name='Expanses',
        ),
    ]
