# Generated by Django 5.0.6 on 2024-06-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_expense_delete_expanses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.dealer'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='exp_type',
            field=models.CharField(choices=[('buy_duck', 'Buy Duck'), ('feed', 'Feed'), ('medicine', 'Medicine'), ('other_stocks', 'Other Stocks'), ('others', 'Others')], max_length=100),
        ),
    ]
