# Generated by Django 5.0.6 on 2024-06-20 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_expense_dealer_alter_expense_exp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.dealer')),
            ],
        ),
    ]
