# Generated by Django 5.0.6 on 2024-06-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_currentfeed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentfeed',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
